In [1]:
import pandas as pd
import matplotlib as plt
import re
import numpy as np
import datetime

In [2]:
exit_notes_df = pd.read_excel(r'C:\Users\David Chaniott\Documents\Nashville Software School\python\projects\ddid-cheesecake_factory\data/idea.xlsx', sheet_name = 'Exit Notes')

In [3]:
# Check for text 'Reopened'
reopened_df = exit_notes_df[exit_notes_df['Exit Note'].str.contains('reopened:', case=False, na=False)].reset_index(drop=True)

In [4]:
# Drop Unused Columns
reopened_df = reopened_df.drop(columns=['POE', 'DOB', 'Notification Date', 'Initial Eligibility Date'])

In [5]:
# findall. 'Reopened: ##/##/####'
reopened_df['reopened_dates'] = reopened_df['Exit Note'].str.findall('Reopened: \d{2}/\d{2}/\d{4}')

In [6]:
reopened_df['reopened_dates'] = reopened_df['Exit Note'].str.findall('Reopened: \\d{2}/\\d{2}/\\d{4}')
reopened_df['exit_dates'] = reopened_df['Exit Note'].str.findall('Exit Date: \\d{2}/\\d{2}/\\d{4}')

# Creates two new Dataframes
# <reopen_date_df> & <exit_date_df>
reopen_date_df = reopened_df.reopened_dates.to_frame().astype(str)
exit_date_df = reopened_df.exit_dates.to_frame().astype(str)

#Splits the columns
reopen_date_df = reopen_date_df.reopened_dates.str.split(',', expand=True)
exit_date_df = exit_date_df.exit_dates.str.split(',', expand=True)

# Names the Columns
reopen_date_df.columns = ['reopen1', 'reopen2', 'reopen3', 'reopen4', 'reopen5', 'reopen6']
exit_date_df.columns = ['exit1', 'exit2', 'exit3', 'exit4', 'exit5', 'exit6']

# Creates <cols_r> & <cols_e> then strips text from them
cols_r = ['reopen1', 'reopen2', 'reopen3', 'reopen4', 'reopen5', 'reopen6']
cols_e = ['exit1', 'exit2', 'exit3', 'exit4', 'exit5', 'exit6']
reopen_date_df[cols_r] = reopen_date_df[cols_r].replace({'\[':'', '\]':'', '\'':'', 'Reopened:':''}, regex=True)
exit_date_df[cols_e] = exit_date_df[cols_e].replace({'\[':'', '\]':'', '\'':'', 'Exit Date:':''}, regex=True)

In [7]:
# Convert Data Types to datetime
reopen_date_df = reopen_date_df.astype('datetime64')
exit_date_df = exit_date_df.astype('datetime64')

In [8]:
# Join exit and reopen
reopen_exit_date_df = reopen_date_df.join(exit_date_df)

In [9]:
# Assign new column with 0 'days'
reopen_exit_date_df['days1'] = np.timedelta64(0)
reopen_exit_date_df['days2'] = np.timedelta64(0)
reopen_exit_date_df['days3'] = np.timedelta64(0)
reopen_exit_date_df['days4'] = np.timedelta64(0)
reopen_exit_date_df['days5'] = np.timedelta64(0)
reopen_exit_date_df['days6'] = np.timedelta64(0)

In [10]:
def awesome(R,E) :
    
    difference = (R - E)
    return(difference)

In [11]:
for index, row in reopen_exit_date_df.iterrows() :
    
    #days1
    
    r = row['reopen1']
    e = row['exit1']
    reopen_exit_date_df.at[index, 'days1'] = awesome(r,e)
    
    #days2
    
    r = row['reopen2']
    e = row['exit2']
    reopen_exit_date_df.at[index, 'days2'] = awesome(r,e)
    
    #days3
    
    r = row['reopen3']
    e = row['exit3']
    reopen_exit_date_df.at[index, 'days3'] = awesome(r,e)
    
    #days4
    
    r = row['reopen4']
    e = row['exit4']
    reopen_exit_date_df.at[index, 'days4'] = awesome(r,e)
    
    #days5
    
    r = row['reopen5']
    e = row['exit5']
    reopen_exit_date_df.at[index, 'days5'] = awesome(r,e)
    
    #days6
    
    r = row['reopen6']
    e = row['exit6']
    reopen_exit_date_df.at[index, 'days6'] = awesome(r,e)

In [12]:
days_only_df = reopen_exit_date_df.drop(columns=['reopen1', 'reopen2', 'reopen3', 'reopen4', 'reopen4', 'reopen5', 'reopen6', 'exit1', 'exit2', 'exit3', 'exit4', 'exit5', 'exit6'])

In [13]:
days_only_df = days_only_df[['days1', 'days2', 'days3', 'days4', 'days5' , 'days6']].fillna(pd.Timedelta(days =0))

In [14]:
days_only_df.head(50)

      days1     days2    days3    days4   days5  days6
0  132 days    0 days   0 days   0 days  0 days 0 days
1  304 days    0 days   0 days   0 days  0 days 0 days
2  208 days    0 days   0 days   0 days  0 days 0 days
3   85 days    0 days   0 days   0 days  0 days 0 days
4  148 days    0 days   0 days   0 days  0 days 0 days
5   59 days   70 days  56 days   0 days  0 days 0 days
6  105 days    0 days   0 days   0 days  0 days 0 days
7  218 days   13 days   0 days   0 days  0 days 0 days
8    4 days    0 days   0 days   0 days  0 days 0 days
9  431 days -150 days   0 days   0 days  0 days 0 days
10  21 days    0 days   0 days   0 days  0 days 0 days
11 181 days    0 days   0 days   0 days  0 days 0 days
12  64 days   50 days   0 days   0 days  0 days 0 days
13  81 days  175 days   0 days   0 days  0 days 0 days
14  84 days    0 days   0 days   0 days  0 days 0 days
15  60 days    0 days   0 days   0 days  0 days 0 days
16 497 days    0 days  98 days   0 days  0 days 0 days
17 497 days   98 days   0 days   0 days  0 days 0 days
18   6 days  402 days   0 days   0 days  0 days 0 days
19  51 days  271 days   0 days   0 days  0 days 0 days
20 210 days  348 days   0 days   0 days  0 days 0 days
21  16 days    0 days   0 days   0 days  0 days 0 days
22  63 days    0 days   0 days   0 days  0 days 0 days
23  17 days   64 days   0 days   0 days  0 days 0 days
24  70 days  229 days   0 days   0 days  0 days 0 days
25 118 days    0 days   0 days   0 days  0 days 0 days
26  18 days   34 days  13 days  83 days 85 days 0 days
27 224 days    0 days   0 days   0 days  0 days 0 days
28  20 days    0 days   0 days   0 days  0 days 0 days
29  57 days    0 days   0 days   0 days  0 days 0 days
30 285 days   25 days  43 days   0 days  0 days 0 days
31  25 days    0 days   0 days   0 days  0 days 0 days
32  89 days    0 days   0 days   0 days  0 days 0 days
33 163 days   18 days   0 days   0 days  0 days 0 days
34  20 days    0 days   0 days   0 days  0 days 0 days
35 253 days   67 days   0 days   0 days  0 days 0 days
36  64 days    0 days   0 days   0 days  0 days 0 days
37 356 days    0 days   0 days   0 days  0 days 0 days
38 100 days    0 days   0 days   0 days  0 days 0 days
39 145 days  340 days   9 days 159 days  0 days 0 days
40   7 days    0 days   0 days   0 days  0 days 0 days
41  53 days   29 days  94 days   0 days  0 days 0 days
42  52 days    0 days   0 days   0 days  0 days 0 days
43 539 days    8 days  21 days   0 days  0 days 0 days
44 288 days    0 days   0 days   0 days  0 days 0 days
45 288 days    0 days   0 days   0 days  0 days 0 days
46  51 days    0 days   0 days   0 days  0 days 0 days
47 554 days    0 days   0 days   0 days  0 days 0 days
48  48 days   47 days   0 days   0 days  0 days 0 days
49 175 days   14 days 127 days  18 days  0 days 0 days

In [15]:
total_days_df = pd.DataFrame(days_only_df['days1']+days_only_df['days2']+days_only_df['days3']+days_only_df['days4']+days_only_df['days5']+days_only_df['days6'])
total_days_df.head(50)

          0
0  132 days
1  304 days
2  208 days
3   85 days
4  148 days
5  185 days
6  105 days
7  231 days
8    4 days
9  281 days
10  21 days
11 181 days
12 114 days
13 256 days
14  84 days
15  60 days
16 595 days
17 595 days
18 408 days
19 322 days
20 558 days
21  16 days
22  63 days
23  81 days
24 299 days
25 118 days
26 233 days
27 224 days
28  20 days
29  57 days
30 353 days
31  25 days
32  89 days
33 181 days
34  20 days
35 320 days
36  64 days
37 356 days
38 100 days
39 653 days
40   7 days
41 176 days
42  52 days
43 568 days
44 288 days
45 288 days
46  51 days
47 554 days
48  95 days
49 334 days

In [16]:
total_days_df.describe()

                                 0
count                         1730
mean   184 days 21:39:19.768786128
std    216 days 03:22:01.279416632
min           -1032 days +00:00:00
25%               35 days 06:00:00
50%              141 days 12:00:00
75%              303 days 00:00:00
max             1000 days 00:00:00

In [17]:
reopen_exit_date_df.head()

,reopen1,reopen2,reopen3,reopen4,reopen5,reopen6,exit1,exit2,exit3,exit4,exit5,exit6,days1,days2,days3,days4,days5,days6
0,2020-04-06,NaT,NaT,NaT,NaT,NaT,2019-11-26,NaT,NaT,NaT,NaT,NaT,132 days,NaT,NaT,NaT,NaT,NaT
1,2021-02-05,NaT,NaT,NaT,NaT,NaT,2020-04-07,NaT,NaT,NaT,NaT,NaT,304 days,NaT,NaT,NaT,NaT,NaT
2,2019-01-11,NaT,NaT,NaT,NaT,NaT,2018-06-17,NaT,NaT,NaT,NaT,NaT,208 days,NaT,NaT,NaT,NaT,NaT
3,2020-02-28,NaT,NaT,NaT,NaT,NaT,2019-12-05,NaT,NaT,NaT,NaT,NaT,85 days,NaT,NaT,NaT,NaT,NaT
4,2020-08-04,NaT,NaT,NaT,NaT,NaT,2020-03-09,NaT,NaT,NaT,NaT,NaT,148 days,NaT,NaT,NaT,NaT,NaT

In [18]:
exit_notes_df.head()

,POE,Child ID,DOB,Notification Date,Initial Eligibility Date,Initial IFSP Date,Latest IFSP Date,Exit Reason,Exit Date,Days from I-IFSP to Exit,Exit Note
0,UC,471738,2019-02-28,2019-10-17,2019-10-29,2019-10-31,2020-05-12,618 - Parent withdraw,2020-09-21,326,* No Exit ECO available due to COVID-19
1,FT,449030,2018-07-22,2018-11-07,2018-12-03,2018-12-18,2021-03-04,618 - Moved out of state,2021-03-06,809,"***family moving out of state March 2021, and ..."
2,FT,463311,2017-07-09,2019-05-24,2019-06-19,2019-07-02,2020-06-22,618 - Part B eligibility not determined,2020-07-08,372,**Completed the transition planning conference...
3,FT,463313,2017-07-09,2019-05-24,2019-06-19,2019-07-02,2020-06-22,618 - Part B eligibility not determined,2020-07-08,372,**Completed the transition planning conference...
4,FT,469194,2017-08-31,2019-09-04,2019-10-02,2019-10-11,2020-05-26,618 - Part B eligibility not determined,2020-08-30,324,**Due to the impact of the COVID-19 pandemic a...

In [19]:
reopened_df.head()

,Child ID,Initial IFSP Date,Latest IFSP Date,Exit Reason,Exit Date,Days from I-IFSP to Exit,Exit Note,reopened_dates,exit_dates
0,473474,2020-05-06,2020-06-23,618 - Part B eligibility not determined,2020-11-04,182,**LEA county on the Transition page and demogr...,[Reopened: 04/06/2020],[Exit Date: 11/26/2019]
1,469243,2019-10-02,2020-03-19,618 - Parent withdraw,2021-02-11,498,02-11-2021 – PWN signed and returned for volun...,[Reopened: 02/05/2021],[Exit Date: 04/07/2020]
2,436339,2019-02-13,2021-01-29,618 - Part B eligibility not determined,2021-04-01,778,04/01/2021- File closed business day prior to ...,[Reopened: 01/11/2019],[Exit Date: 06/17/2018]
3,474102,2020-04-09,2021-03-29,618 - Part B eligibility not determined,2021-05-10,396,05/10/2021 TPC held then parents withdrew from...,[Reopened: 02/28/2020],[Exit Date: 12/05/2019]
4,476958,2020-08-24,2021-02-12,618 - Parent withdraw,2021-05-25,274,05/25/21- parent withdraw Reopened: 08/04/2020...,[Reopened: 08/04/2020],[Exit Date: 03/09/2020]